# Generated by Django 2.2.11 on 2020-04-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='used_invitation',
            new_name='used_invitations',
        ),
    ]
